// Dependencies
var PropagatingEvent = Framework.require('system/events/PropagatingEvent.js');

// Class
var HtmlEvent = PropagatingEvent.extend({

	domEvent: null, // The native event emitted by the DOM
	trusted: null, // Set to true if the event was generated by a user action, and false when the event was created or modified by a script or dispatched via dispatchEvent

});

// Static methods

HtmlEvent.is = function(value) {
	return Class.isInstance(value, HtmlEvent);
};

// Export
module.exports = HtmlEvent;