// Object
var FileFormats = {
	'123': 			{ 'extension': '123',			'type': 'application/vnd.lotus-1-2-3',														'description': 'Lotus 1-2-3' },
	'3dml': 		{ 'extension': '3dml',			'type': 'text/vnd.in3d.3dml',																'description': 'In3D - 3DML' },
	'3g2': 			{ 'extension': '3g2',			'type': 'video/3gpp2',																		'description': '3GP2' },
	'3gp': 			{ 'extension': '3gp',			'type': 'video/3gpp',																		'description': '3GP' },
	'7z': 			{ 'extension': '7z',			'type': 'application/x-7z-compressed',														'description': '7-Zip' },
	'aab': 			{ 'extension': 'aab',			'type': 'application/x-authorware-bin',														'description': 'Adobe (Macropedia) Authorware - Binary File' },
	'aac': 			{ 'extension': 'aac',			'type': 'audio/x-aac',																		'description': 'Advanced Audio Coding (AAC)' },
	'aam': 			{ 'extension': 'aam',			'type': 'application/x-authorware-map',														'description': 'Adobe (Macropedia) Authorware - Map' },
	'aas': 			{ 'extension': 'aas',			'type': 'application/x-authorware-seg',														'description': 'Adobe (Macropedia) Authorware - Segment File' },
	'abw': 			{ 'extension': 'abw',			'type': 'application/x-abiword',															'description': 'AbiWord' },
	'ac': 			{ 'extension': 'ac',			'type': 'application/pkix-attr-cert',														'description': 'Attribute Certificate' },
	'acc': 			{ 'extension': 'acc',			'type': 'application/vnd.americandynamics.acc',												'description': 'Active Content Compression' },
	'ace': 			{ 'extension': 'ace',			'type': 'application/x-ace-compressed',														'description': 'Ace Archive' },
	'acu': 			{ 'extension': 'acu',			'type': 'application/vnd.acucobol',															'description': 'ACU Cobol' },
	'adp': 			{ 'extension': 'adp',			'type': 'audio/adpcm',																		'description': 'Adaptive differential pulse-code modulation' },
	'aep': 			{ 'extension': 'aep',			'type': 'application/vnd.audiograph',														'description': 'Audiograph' },
	'afp': 			{ 'extension': 'afp',			'type': 'application/vnd.ibm.modcap',														'description': 'MO:DCA-P' },
	'ahead': 		{ 'extension': 'ahead',			'type': 'application/vnd.ahead.space',														'description': 'Ahead AIR Application' },
	'ai': 			{ 'extension': 'ai',			'type': 'application/postscript',															'description': 'PostScript' },
	'aif': 			{ 'extension': 'aif',			'type': 'audio/x-aiff',																		'description': 'Audio Interchange File Format' },
	'air': 			{ 'extension': 'air',			'type': 'application/vnd.adobe.air-application-installer-package+zip',						'description': 'Adobe AIR Application' },
	'ait': 			{ 'extension': 'ait',			'type': 'application/vnd.dvb.ait',															'description': 'Digital Video Broadcasting' },
	'ami': 			{ 'extension': 'ami',			'type': 'application/vnd.amiga.ami',														'description': 'AmigaDE' },
	'apk': 			{ 'extension': 'apk',			'type': 'application/vnd.android.package-archive',											'description': 'Android Package Archive' },
	'application': 	{ 'extension': 'application',	'type': 'application/x-ms-application',														'description': 'Microsoft ClickOnce' },
	'apr': 			{ 'extension': 'apr',			'type': 'application/vnd.lotus-approach',													'description': 'Lotus Approach' },
	'asf': 			{ 'extension': 'asf',			'type': 'video/x-ms-asf',																	'description': 'Microsoft Advanced Systems Format (ASF)' },
	'aso': 			{ 'extension': 'aso',			'type': 'application/vnd.accpac.simply.aso',												'description': 'Simply Accounting' },
	'atc': 			{ 'extension': 'atc',			'type': 'application/vnd.acucorp',															'description': 'ACU Cobol' },
	'atom': 		{ 'extension': 'atom',			'type': 'application/atom+xml',																'description': 'Atom Syndication Format' },
	'atomcat': 		{ 'extension': 'atomcat',		'type': 'application/atomcat+xml',															'description': 'Atom Publishing Protocol' },
	'atomsvc': 		{ 'extension': 'atomsvc',		'type': 'application/atomsvc+xml',															'description': 'Atom Publishing Protocol Service Document' },
	'atx': 			{ 'extension': 'atx',			'type': 'application/vnd.antix.game-component',												'description': 'Antix Game Player' },
	'au': 			{ 'extension': 'au',			'type': 'audio/basic',																		'description': 'Sun Audio - Au file format' },
	'avi': 			{ 'extension': 'avi',			'type': 'video/x-msvideo',																	'description': 'Audio Video Interleave (AVI)' },
	'aw': 			{ 'extension': 'aw',			'type': 'application/applixware',															'description': 'Applixware' },
	'azf': 			{ 'extension': 'azf',			'type': 'application/vnd.airzip.filesecure.azf',											'description': 'AirZip FileSECURE' },
	'azs': 			{ 'extension': 'azs',			'type': 'application/vnd.airzip.filesecure.azs',											'description': 'AirZip FileSECURE' },
	'azw': 			{ 'extension': 'azw',			'type': 'application/vnd.amazon.ebook',														'description': 'Amazon Kindle eBook format' },
	'bcpio': 		{ 'extension': 'bcpio',			'type': 'application/x-bcpio',																'description': 'Binary CPIO Archive' },
	'bdf': 			{ 'extension': 'bdf',			'type': 'application/x-font-bdf',															'description': 'Glyph Bitmap Distribution Format' },
	'bdm': 			{ 'extension': 'bdm',			'type': 'application/vnd.syncml.dm+wbxml',													'description': 'SyncML - Device Management' },
	'bed': 			{ 'extension': 'bed',			'type': 'application/vnd.realvnc.bed',														'description': 'RealVNC' },
	'bh2': 			{ 'extension': 'bh2',			'type': 'application/vnd.fujitsu.oasysprs',													'description': 'Fujitsu Oasys' },
	'bin': 			{ 'extension': 'bin',			'type': 'application/octet-stream',															'description': 'Binary Data' },
	'bmi': 			{ 'extension': 'bmi',			'type': 'application/vnd.bmi',																'description': 'BMI Drawing Data Interchange' },
	'bmp': 			{ 'extension': 'bmp',			'type': 'image/bmp',																		'description': 'Bitmap Image File' },
	'box': 			{ 'extension': 'box',			'type': 'application/vnd.previewsystems.box',												'description': 'Preview Systems ZipLock/VBox' },
	'btif': 		{ 'extension': 'btif',			'type': 'image/prs.btif',																	'description': 'BTIF' },
	'bz': 			{ 'extension': 'bz',			'type': 'application/x-bzip',																'description': 'Bzip Archive' },
	'bz2': 			{ 'extension': 'bz2',			'type': 'application/x-bzip2',																'description': 'Bzip2 Archive' },
	'c': 			{ 'extension': 'c',				'type': 'text/x-c',																			'description': 'C Source File' },
	'c11amc': 		{ 'extension': 'c11amc',		'type': 'application/vnd.cluetrust.cartomobile-config',										'description': 'ClueTrust CartoMobile - Config' },
	'c11amz': 		{ 'extension': 'c11amz',		'type': 'application/vnd.cluetrust.cartomobile-config-pkg',									'description': 'ClueTrust CartoMobile - Config Package' },
	'c4g': 			{ 'extension': 'c4g',			'type': 'application/vnd.clonk.c4group',													'description': 'Clonk Game' },
	'cab': 			{ 'extension': 'cab',			'type': 'application/vnd.ms-cab-compressed',												'description': 'Microsoft Cabinet File' },
	'car': 			{ 'extension': 'car',			'type': 'application/vnd.curl.car',															'description': 'CURL Applet' },
	'cat': 			{ 'extension': 'cat',			'type': 'application/vnd.ms-pki.seccat',													'description': 'Microsoft Trust UI Provider - Security Catalog' },
	'ccxml': 		{ 'extension': 'ccxml',			'type': 'application/ccxml+xml',															'description': 'Voice Browser Call Control' },
	'cdbcmsg': 		{ 'extension': 'cdbcmsg',		'type': 'application/vnd.contact.cmsg',														'description': 'CIM Database' },
	'cdkey': 		{ 'extension': 'cdkey',			'type': 'application/vnd.mediastation.cdkey',												'description': 'MediaRemote' },
	'cdmia': 		{ 'extension': 'cdmia',			'type': 'application/cdmi-capability',														'description': 'Cloud Data Management Interface (CDMI) - Capability' },
	'cdmic': 		{ 'extension': 'cdmic',			'type': 'application/cdmi-container',														'description': 'Cloud Data Management Interface (CDMI) - Contaimer' },
	'cdmid': 		{ 'extension': 'cdmid',			'type': 'application/cdmi-domain',															'description': 'Cloud Data Management Interface (CDMI) - Domain' },
	'cdmio': 		{ 'extension': 'cdmio',			'type': 'application/cdmi-object',															'description': 'Cloud Data Management Interface (CDMI) - Object' },
	'cdmiq': 		{ 'extension': 'cdmiq',			'type': 'application/cdmi-queue',															'description': 'Cloud Data Management Interface (CDMI) - Queue' },
	'cdx': 			{ 'extension': 'cdx',			'type': 'chemical/x-cdx',																	'description': 'ChemDraw eXchange file' },
	'cdxml': 		{ 'extension': 'cdxml',			'type': 'application/vnd.chemdraw+xml',														'description': 'CambridgeSoft Chem Draw' },
	'cdy': 			{ 'extension': 'cdy',			'type': 'application/vnd.cinderella',														'description': 'Interactive Geometry Software Cinderella' },
	'cer': 			{ 'extension': 'cer',			'type': 'application/pkix-cert',															'description': 'Internet Public Key Infrastructure - Certificate' },
	'cgm': 			{ 'extension': 'cgm',			'type': 'image/cgm',																		'description': 'Computer Graphics Metafile' },
	'chat': 		{ 'extension': 'chat',			'type': 'application/x-chat',																'description': 'pIRCh' },
	'chm': 			{ 'extension': 'chm',			'type': 'application/vnd.ms-htmlhelp',														'description': 'Microsoft Html Help File' },
	'chrt': 		{ 'extension': 'chrt',			'type': 'application/vnd.kde.kchart',														'description': 'KDE KOffice Office Suite - KChart' },
	'cif': 			{ 'extension': 'cif',			'type': 'chemical/x-cif',																	'description': 'Crystallographic Interchange Format' },
	'cii': 			{ 'extension': 'cii',			'type': 'application/vnd.anser-web-certificate-issue-initiation',							'description': 'ANSER-WEB Terminal Client - Certificate Issue' },
	'cil': 			{ 'extension': 'cil',			'type': 'application/vnd.ms-artgalry',														'description': 'Microsoft Artgalry' },
	'cla': 			{ 'extension': 'cla',			'type': 'application/vnd.claymore',															'description': 'Claymore Data Files' },
	'class': 		{ 'extension': 'class',			'type': 'application/java-vm',																'description': 'Java Bytecode File' },
	'clkk': 		{ 'extension': 'clkk',			'type': 'application/vnd.crick.clicker.keyboard',											'description': 'CrickSoftware - Clicker - Keyboard' },
	'clkp': 		{ 'extension': 'clkp',			'type': 'application/vnd.crick.clicker.palette',											'description': 'CrickSoftware - Clicker - Palette' },
	'clkt': 		{ 'extension': 'clkt',			'type': 'application/vnd.crick.clicker.template',											'description': 'CrickSoftware - Clicker - Template' },
	'clkw': 		{ 'extension': 'clkw',			'type': 'application/vnd.crick.clicker.wordbank',											'description': 'CrickSoftware - Clicker - Wordbank' },
	'clkx': 		{ 'extension': 'clkx',			'type': 'application/vnd.crick.clicker',													'description': 'CrickSoftware - Clicker' },
	'clp': 			{ 'extension': 'clp',			'type': 'application/x-msclip',																'description': 'Microsoft Clipboard Clip' },
	'cmc': 			{ 'extension': 'cmc',			'type': 'application/vnd.cosmocaller',														'description': 'CosmoCaller' },
	'cmdf': 		{ 'extension': 'cmdf',			'type': 'chemical/x-cmdf',																	'description': 'CrystalMaker Data Format' },
	'cml': 			{ 'extension': 'cml',			'type': 'chemical/x-cml',																	'description': 'Chemical Markup Language' },
	'cmp': 			{ 'extension': 'cmp',			'type': 'application/vnd.yellowriver-custom-menu',											'description': 'CustomMenu' },
	'cmx': 			{ 'extension': 'cmx',			'type': 'image/x-cmx',																		'description': 'Corel Metafile Exchange (CMX)' },
	'cod': 			{ 'extension': 'cod',			'type': 'application/vnd.rim.cod',															'description': 'Blackberry COD File' },
	'cpio': 		{ 'extension': 'cpio',			'type': 'application/x-cpio',																'description': 'CPIO Archive' },
	'cpt': 			{ 'extension': 'cpt',			'type': 'application/mac-compactpro',														'description': 'Compact Pro' },
	'crd': 			{ 'extension': 'crd',			'type': 'application/x-mscardfile',															'description': 'Microsoft Information Card' },
	'crl': 			{ 'extension': 'crl',			'type': 'application/pkix-crl',																'description': 'Internet Public Key Infrastructure - Certificate Revocation Lists' },
	'cryptonote': 	{ 'extension': 'cryptonote',	'type': 'application/vnd.rig.cryptonote',													'description': 'CryptoNote' },
	'csh': 			{ 'extension': 'csh',			'type': 'application/x-csh',																'description': 'C Shell Script' },
	'csml': 		{ 'extension': 'csml',			'type': 'chemical/x-csml',																	'description': 'Chemical Style Markup Language' },
	'csp': 			{ 'extension': 'csp',			'type': 'application/vnd.commonspace',														'description': 'Sixth Floor Media - CommonSpace' },
	'css': 			{ 'extension': 'css',			'type': 'text/css',																			'description': 'Cascading Style Sheets (CSS)' },
	'csv': 			{ 'extension': 'csv',			'type': 'text/csv',																			'description': 'Comma-Seperated Values' },
	'cu': 			{ 'extension': 'cu',			'type': 'application/cu-seeme',																'description': 'CU-SeeMe' },
	'curl': 		{ 'extension': 'curl',			'type': 'text/vnd.curl',																	'description': 'Curl - Applet' },
	'cww': 			{ 'extension': 'cww',			'type': 'application/prs.cww',																'description': 'CU-Writer' },
	'dae': 			{ 'extension': 'dae',			'type': 'model/vnd.collada+xml',															'description': 'COLLADA' },
	'daf': 			{ 'extension': 'daf',			'type': 'application/vnd.mobius.daf',														'description': 'Mobius Management Systems - UniversalArchive' },
	'davmount': 	{ 'extension': 'davmount',		'type': 'application/davmount+xml',															'description': 'Web Distributed Authoring and Versioning' },
	'dcurl': 		{ 'extension': 'dcurl',			'type': 'text/vnd.curl.dcurl',																'description': 'Curl - Detached Applet' },
	'dd2': 			{ 'extension': 'dd2',			'type': 'application/vnd.oma.dd2+xml',														'description': 'OMA Download Agents' },
	'ddd': 			{ 'extension': 'ddd',			'type': 'application/vnd.fujixerox.ddd',													'description': 'Fujitsu - Xerox 2D CAD Data' },
	'deb': 			{ 'extension': 'deb',			'type': 'application/x-debian-package',														'description': 'Debian Package' },
	'der': 			{ 'extension': 'der',			'type': 'application/x-x509-ca-cert',														'description': 'X.509 Certificate' },
	'dfac': 		{ 'extension': 'dfac',			'type': 'application/vnd.dreamfactory',														'description': 'DreamFactory' },
	'dir': 			{ 'extension': 'dir',			'type': 'application/x-director',															'description': 'Adobe Shockwave Player' },
	'dis': 			{ 'extension': 'dis',			'type': 'application/vnd.mobius.dis',														'description': 'Mobius Management Systems - Distribution Database' },
	'djvu': 		{ 'extension': 'djvu',			'type': 'image/vnd.djvu',																	'description': 'DjVu' },
	'dna': 			{ 'extension': 'dna',			'type': 'application/vnd.dna',																'description': 'New Moon Liftoff/DNA' },
	'doc': 			{ 'extension': 'doc',			'type': 'application/msword',																'description': 'Microsoft Word' },
	'docm': 		{ 'extension': 'docm',			'type': 'application/vnd.ms-word.document.macroenabled.12',									'description': 'Micosoft Word - Macro-Enabled Document' },
	'docx': 		{ 'extension': 'docx',			'type': 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',			'description': 'Microsoft Office - OOXML - Word Document' },
	'dotm': 		{ 'extension': 'dotm',			'type': 'application/vnd.ms-word.template.macroenabled.12',									'description': 'Micosoft Word - Macro-Enabled Template' },
	'dotx': 		{ 'extension': 'dotx',			'type': 'application/vnd.openxmlformats-officedocument.wordprocessingml.template',			'description': 'Microsoft Office - OOXML - Word Document Template' },
	'dp': 			{ 'extension': 'dp',			'type': 'application/vnd.osgi.dp',															'description': 'OSGi Deployment Package' },
	'dpg': 			{ 'extension': 'dpg',			'type': 'application/vnd.dpgraph',															'description': 'DPGraph' },
	'dra': 			{ 'extension': 'dra',			'type': 'audio/vnd.dra',																	'description': 'DRA Audio' },
	'dsc': 			{ 'extension': 'dsc',			'type': 'text/prs.lines.tag',																'description': 'PRS Lines Tag' },
	'dssc': 		{ 'extension': 'dssc',			'type': 'application/dssc+der',																'description': 'Data Structure for the Security Suitability of Cryptographic Algorithms' },
	'dtb': 			{ 'extension': 'dtb',			'type': 'application/x-dtbook+xml',															'description': 'Digital Talking Book' },
	'dtd': 			{ 'extension': 'dtd',			'type': 'application/xml-dtd',																'description': 'Document Type Definition' },
	'dts': 			{ 'extension': 'dts',			'type': 'audio/vnd.dts',																	'description': 'DTS Audio' },
	'dtshd': 		{ 'extension': 'dtshd',			'type': 'audio/vnd.dts.hd',																	'description': 'DTS High Definition Audio' },
	'dvi': 			{ 'extension': 'dvi',			'type': 'application/x-dvi',																'description': 'Device Independent File Format (DVI)' },
	'dwf': 			{ 'extension': 'dwf',			'type': 'model/vnd.dwf',																	'description': 'Autodesk Design Web Format (DWF)' },
	'dwg': 			{ 'extension': 'dwg',			'type': 'image/vnd.dwg',																	'description': 'DWG Drawing' },
	'dxf': 			{ 'extension': 'dxf',			'type': 'image/vnd.dxf',																	'description': 'AutoCAD DXF' },
	'dxp': 			{ 'extension': 'dxp',			'type': 'application/vnd.spotfire.dxp',														'description': 'TIBCO Spotfire' },
	'ecelp4800': 	{ 'extension': 'ecelp4800',		'type': 'audio/vnd.nuera.ecelp4800',														'description': 'Nuera ECELP 4800' },
	'ecelp7470': 	{ 'extension': 'ecelp7470',		'type': 'audio/vnd.nuera.ecelp7470',														'description': 'Nuera ECELP 7470' },
	'ecelp9600': 	{ 'extension': 'ecelp9600',		'type': 'audio/vnd.nuera.ecelp9600',														'description': 'Nuera ECELP 9600' },
	'edm': 			{ 'extension': 'edm',			'type': 'application/vnd.novadigm.edm',														'description': 'Novadigm\'s RADIA and EDM products' },
	'edx': 			{ 'extension': 'edx',			'type': 'application/vnd.novadigm.edx',														'description': 'Novadigm\'s RADIA and EDM products' },
	'efif': 		{ 'extension': 'efif',			'type': 'application/vnd.picsel',															'description': 'Pcsel eFIF File' },
	'ei6': 			{ 'extension': 'ei6',			'type': 'application/vnd.pg.osasli',														'description': 'Proprietary P&G Standard Reporting System' },
	'eml': 			{ 'extension': 'eml',			'type': 'message/rfc822',																	'description': 'Email Message' },
	'emma': 		{ 'extension': 'emma',			'type': 'application/emma+xml',																'description': 'Extensible MultiModal Annotation' },
	'eol': 			{ 'extension': 'eol',			'type': 'audio/vnd.digital-winds',															'description': 'Digital Winds Music' },
	'eot': 			{ 'extension': 'eot',			'type': 'application/vnd.ms-fontobject',													'description': 'Microsoft Embedded OpenType' },
	'epub': 		{ 'extension': 'epub',			'type': 'application/epub+zip',																'description': 'Electronic Publication' },
	'es': 			{ 'extension': 'es',			'type': 'application/ecmascript',															'description': 'ECMAScript' },
	'es3': 			{ 'extension': 'es3',			'type': 'application/vnd.eszigno3+xml',														'description': 'MICROSEC e-Szign¢' },
	'esf': 			{ 'extension': 'esf',			'type': 'application/vnd.epson.esf',														'description': 'QUASS Stream Player' },
	'etx': 			{ 'extension': 'etx',			'type': 'text/x-setext',																	'description': 'Setext' },
	'exe': 			{ 'extension': 'exe',			'type': 'application/x-msdownload',															'description': 'Microsoft Application' },
	'exi': 			{ 'extension': 'exi',			'type': 'application/exi',																	'description': 'Efficient XML Interchange' },
	'ext': 			{ 'extension': 'ext',			'type': 'application/vnd.novadigm.ext',														'description': 'Novadigm\'s RADIA and EDM products' },
	'ez2': 			{ 'extension': 'ez2',			'type': 'application/vnd.ezpix-album',														'description': 'EZPix Secure Photo Album' },
	'ez3': 			{ 'extension': 'ez3',			'type': 'application/vnd.ezpix-package',													'description': 'EZPix Secure Photo Album' },
	'f': 			{ 'extension': 'f',				'type': 'text/x-fortran',																	'description': 'Fortran Source File' },
	'f4v': 			{ 'extension': 'f4v',			'type': 'video/x-f4v',																		'description': 'Flash Video' },
	'fbs': 			{ 'extension': 'fbs',			'type': 'image/vnd.fastbidsheet',															'description': 'FastBid Sheet' },
	'fcs': 			{ 'extension': 'fcs',			'type': 'application/vnd.isac.fcs',															'description': 'International Society for Advancement of Cytometry' },
	'fdf': 			{ 'extension': 'fdf',			'type': 'application/vnd.fdf',																'description': 'Forms Data Format' },
	'fe_launch': 	{ 'extension': 'fe_launch',		'type': 'application/vnd.denovo.fcselayout-link',											'description': 'FCS Express Layout Link' },
	'fg5': 			{ 'extension': 'fg5',			'type': 'application/vnd.fujitsu.oasysgp',													'description': 'Fujitsu Oasys' },
	'fh': 			{ 'extension': 'fh',			'type': 'image/x-freehand',																	'description': 'FreeHand MX' },
	'fig': 			{ 'extension': 'fig',			'type': 'application/x-xfig',																'description': 'Xfig' },
	'fli': 			{ 'extension': 'fli',			'type': 'video/x-fli',																		'description': 'FLI/FLC Animation Format' },
	'flo': 			{ 'extension': 'flo',			'type': 'application/vnd.micrografx.flo',													'description': 'Micrografx' },
	'flv': 			{ 'extension': 'flv',			'type': 'video/x-flv',																		'description': 'Flash Video' },
	'flw': 			{ 'extension': 'flw',			'type': 'application/vnd.kde.kivio',														'description': 'KDE KOffice Office Suite - Kivio' },
	'flx': 			{ 'extension': 'flx',			'type': 'text/vnd.fmi.flexstor',															'description': 'FLEXSTOR' },
	'fly': 			{ 'extension': 'fly',			'type': 'text/vnd.fly',																		'description': 'mod_fly / fly.cgi' },
	'fm': 			{ 'extension': 'fm',			'type': 'application/vnd.framemaker',														'description': 'FrameMaker Normal Format' },
	'fnc': 			{ 'extension': 'fnc',			'type': 'application/vnd.frogans.fnc',														'description': 'Frogans Player' },
	'fpx': 			{ 'extension': 'fpx',			'type': 'image/vnd.fpx',																	'description': 'FlashPix' },
	'fsc': 			{ 'extension': 'fsc',			'type': 'application/vnd.fsc.weblaunch',													'description': 'Friendly Software Corporation' },
	'fst': 			{ 'extension': 'fst',			'type': 'image/vnd.fst',																	'description': 'FAST Search & Transfer ASA' },
	'ftc': 			{ 'extension': 'ftc',			'type': 'application/vnd.fluxtime.clip',													'description': 'FluxTime Clip' },
	'fti': 			{ 'extension': 'fti',			'type': 'application/vnd.anser-web-funds-transfer-initiation',								'description': 'ANSER-WEB Terminal Client - Web Funds Transfer' },
	'fvt': 			{ 'extension': 'fvt',			'type': 'video/vnd.fvt',																	'description': 'FAST Search & Transfer ASA' },
	'fxp': 			{ 'extension': 'fxp',			'type': 'application/vnd.adobe.fxp',														'description': 'Adobe Flex Project' },
	'fzs': 			{ 'extension': 'fzs',			'type': 'application/vnd.fuzzysheet',														'description': 'FuzzySheet' },
	'g2w': 			{ 'extension': 'g2w',			'type': 'application/vnd.geoplan',															'description': 'GeoplanW' },
	'g3': 			{ 'extension': 'g3',			'type': 'image/g3fax',																		'description': 'G3 Fax Image' },
	'g3w': 			{ 'extension': 'g3w',			'type': 'application/vnd.geospace',															'description': 'GeospacW' },
	'gac': 			{ 'extension': 'gac',			'type': 'application/vnd.groove-account',													'description': 'Groove - Account' },
	'gdl': 			{ 'extension': 'gdl',			'type': 'model/vnd.gdl',																	'description': 'Geometric Description Language (GDL)' },
	'geo': 			{ 'extension': 'geo',			'type': 'application/vnd.dynageo',															'description': 'DynaGeo' },
	'gex': 			{ 'extension': 'gex',			'type': 'application/vnd.geometry-explorer',												'description': 'GeoMetry Explorer' },
	'ggb': 			{ 'extension': 'ggb',			'type': 'application/vnd.geogebra.file',													'description': 'GeoGebra' },
	'ggt': 			{ 'extension': 'ggt',			'type': 'application/vnd.geogebra.tool',													'description': 'GeoGebra' },
	'ghf': 			{ 'extension': 'ghf',			'type': 'application/vnd.groove-help',														'description': 'Groove - Help' },
	'gif': 			{ 'extension': 'gif',			'type': 'image/gif',																		'description': 'Graphics Interchange Format' },
	'gim': 			{ 'extension': 'gim',			'type': 'application/vnd.groove-identity-message',											'description': 'Groove - Identity Message' },
	'gmx': 			{ 'extension': 'gmx',			'type': 'application/vnd.gmx',																'description': 'GameMaker ActiveX' },
	'gnumeric': 	{ 'extension': 'gnumeric',		'type': 'application/x-gnumeric',															'description': 'Gnumeric' },
	'gph': 			{ 'extension': 'gph',			'type': 'application/vnd.flographit',														'description': 'NpGraphIt' },
	'gqf': 			{ 'extension': 'gqf',			'type': 'application/vnd.grafeq',															'description': 'GrafEq' },
	'gram': 		{ 'extension': 'gram',			'type': 'application/srgs',																	'description': 'Speech Recognition Grammar Specification' },
	'grv': 			{ 'extension': 'grv',			'type': 'application/vnd.groove-injector',													'description': 'Groove - Injector' },
	'grxml': 		{ 'extension': 'grxml',			'type': 'application/srgs+xml',																'description': 'Speech Recognition Grammar Specification - XML' },
	'gsf': 			{ 'extension': 'gsf',			'type': 'application/x-font-ghostscript',													'description': 'Ghostscript Font' },
	'gtar': 		{ 'extension': 'gtar',			'type': 'application/x-gtar',																'description': 'GNU Tar Files' },
	'gtm': 			{ 'extension': 'gtm',			'type': 'application/vnd.groove-tool-message',												'description': 'Groove - Tool Message' },
	'gtw': 			{ 'extension': 'gtw',			'type': 'model/vnd.gtw',																	'description': 'Gen-Trix Studio' },
	'gv': 			{ 'extension': 'gv',			'type': 'text/vnd.graphviz',																'description': 'Graphviz' },
	'gxt': 			{ 'extension': 'gxt',			'type': 'application/vnd.geonext',															'description': 'GEONExT and JSXGraph' },
	'h261': 		{ 'extension': 'h261',			'type': 'video/h261',																		'description': 'H.261' },
	'h263': 		{ 'extension': 'h263',			'type': 'video/h263',																		'description': 'H.263' },
	'h264': 		{ 'extension': 'h264',			'type': 'video/h264',																		'description': 'H.264' },
	'hal': 			{ 'extension': 'hal',			'type': 'application/vnd.hal+xml',															'description': 'Hypertext Application Language' },
	'hbci': 		{ 'extension': 'hbci',			'type': 'application/vnd.hbci',																'description': 'Homebanking Computer Interface (HBCI)' },
	'hdf': 			{ 'extension': 'hdf',			'type': 'application/x-hdf',																'description': 'Hierarchical Data Format' },
	'hlp': 			{ 'extension': 'hlp',			'type': 'application/winhlp',																'description': 'WinHelp' },
	'hpgl': 		{ 'extension': 'hpgl',			'type': 'application/vnd.hp-hpgl',															'description': 'HP-GL/2 and HP RTL' },
	'hpid': 		{ 'extension': 'hpid',			'type': 'application/vnd.hp-hpid',															'description': 'Hewlett Packard Instant Delivery' },
	'hps': 			{ 'extension': 'hps',			'type': 'application/vnd.hp-hps',															'description': 'Hewlett-Packard\'s WebPrintSmart' },
	'hqx': 			{ 'extension': 'hqx',			'type': 'application/mac-binhex40',															'description': 'Macintosh BinHex 4.0' },
	'htke': 		{ 'extension': 'htke',			'type': 'application/vnd.kenameaapp',														'description': 'Kenamea App' },
	'html': 		{ 'extension': 'html',			'type': 'text/html',																		'description': 'HyperText Markup Language (HTML)' },
	'hvd': 			{ 'extension': 'hvd',			'type': 'application/vnd.yamaha.hv-dic',													'description': 'HV Voice Dictionary' },
	'hvp': 			{ 'extension': 'hvp',			'type': 'application/vnd.yamaha.hv-voice',													'description': 'HV Voice Parameter' },
	'hvs': 			{ 'extension': 'hvs',			'type': 'application/vnd.yamaha.hv-script',													'description': 'HV Script' },
	'i2g': 			{ 'extension': 'i2g',			'type': 'application/vnd.intergeo',															'description': 'Interactive Geometry Software' },
	'icc': 			{ 'extension': 'icc',			'type': 'application/vnd.iccprofile',														'description': 'ICC profile' },
	'ice': 			{ 'extension': 'ice',			'type': 'x-conference/x-cooltalk',															'description': 'CoolTalk' },
	'ico': 			{ 'extension': 'ico',			'type': 'image/x-icon',																		'description': 'Icon Image' },
	'ics': 			{ 'extension': 'ics',			'type': 'text/calendar',																	'description': 'iCalendar' },
	'ief': 			{ 'extension': 'ief',			'type': 'image/ief',																		'description': 'Image Exchange Format' },
	'ifm': 			{ 'extension': 'ifm',			'type': 'application/vnd.shana.informed.formdata',											'description': 'Shana Informed Filler' },
	'igl': 			{ 'extension': 'igl',			'type': 'application/vnd.igloader',															'description': 'igLoader' },
	'igm': 			{ 'extension': 'igm',			'type': 'application/vnd.insors.igm',														'description': 'IOCOM Visimeet' },
	'igs': 			{ 'extension': 'igs',			'type': 'model/iges',																		'description': 'Initial Graphics Exchange Specification (IGES)' },
	'igx': 			{ 'extension': 'igx',			'type': 'application/vnd.micrografx.igx',													'description': 'Micrografx iGrafx Professional' },
	'iif': 			{ 'extension': 'iif',			'type': 'application/vnd.shana.informed.interchange',										'description': 'Shana Informed Filler' },
	'imp': 			{ 'extension': 'imp',			'type': 'application/vnd.accpac.simply.imp',												'description': 'Simply Accounting - Data Import' },
	'ims': 			{ 'extension': 'ims',			'type': 'application/vnd.ms-ims',															'description': 'Microsoft Class Server' },
	'ipfix': 		{ 'extension': 'ipfix',			'type': 'application/ipfix',																'description': 'Internet Protocol Flow Information Export' },
	'ipk': 			{ 'extension': 'ipk',			'type': 'application/vnd.shana.informed.package',											'description': 'Shana Informed Filler' },
	'irm': 			{ 'extension': 'irm',			'type': 'application/vnd.ibm.rights-management',											'description': 'IBM DB2 Rights Manager' },
	'irp': 			{ 'extension': 'irp',			'type': 'application/vnd.irepository.package+xml',											'description': 'iRepository / Lucidoc Editor' },
	'itp': 			{ 'extension': 'itp',			'type': 'application/vnd.shana.informed.formtemplate',										'description': 'Shana Informed Filler' },
	'ivp': 			{ 'extension': 'ivp',			'type': 'application/vnd.immervision-ivp',													'description': 'ImmerVision PURE Players' },
	'ivu': 			{ 'extension': 'ivu',			'type': 'application/vnd.immervision-ivu',													'description': 'ImmerVision PURE Players' },
	'jad': 			{ 'extension': 'jad',			'type': 'text/vnd.sun.j2me.app-descriptor',													'description': 'J2ME App Descriptor' },
	'jam': 			{ 'extension': 'jam',			'type': 'application/vnd.jam',																'description': 'Lightspeed Audio Lab' },
	'jar': 			{ 'extension': 'jar',			'type': 'application/java-archive',															'description': 'Java Archive' },
	'java': 		{ 'extension': 'java',			'type': 'text/x-java-source,java',															'description': 'Java Source File' },
	'jisp': 		{ 'extension': 'jisp',			'type': 'application/vnd.jisp',																'description': 'RhymBox' },
	'jlt': 			{ 'extension': 'jlt',			'type': 'application/vnd.hp-jlyt',															'description': 'HP Indigo Digital Press - Job Layout Languate' },
	'jnlp': 		{ 'extension': 'jnlp',			'type': 'application/x-java-jnlp-file',														'description': 'Java Network Launching Protocol' },
	'joda': 		{ 'extension': 'joda',			'type': 'application/vnd.joost.joda-archive',												'description': 'Joda Archive' },
	'jpg': 			{ 'extension': 'jpg',			'type': 'image/jpeg',																		'description': 'JPEG Image' },
	'jpeg': 		{ 'extension': 'jpeg',			'type': 'image/jpeg',																		'description': 'JPEG Image' },
	'jpgv': 		{ 'extension': 'jpgv',			'type': 'video/jpeg',																		'description': 'JPGVideo' },
	'jpm': 			{ 'extension': 'jpm',			'type': 'video/jpm',																		'description': 'JPEG 2000 Compound Image File Format' },
	'js': 			{ 'extension': 'js',			'type': 'application/javascript',															'description': 'JavaScript' },
	'json': 		{ 'extension': 'json',			'type': 'application/json',																	'description': 'JavaScript Object Notation (JSON)' },
	'karbon': 		{ 'extension': 'karbon',		'type': 'application/vnd.kde.karbon',														'description': 'KDE KOffice Office Suite - Karbon' },
	'kfo': 			{ 'extension': 'kfo',			'type': 'application/vnd.kde.kformula',														'description': 'KDE KOffice Office Suite - Kformula' },
	'kia': 			{ 'extension': 'kia',			'type': 'application/vnd.kidspiration',														'description': 'Kidspiration' },
	'kml': 			{ 'extension': 'kml',			'type': 'application/vnd.google-earth.kml+xml',												'description': 'Google Earth - KML' },
	'kmz': 			{ 'extension': 'kmz',			'type': 'application/vnd.google-earth.kmz',													'description': 'Google Earth - Zipped KML' },
	'kne': 			{ 'extension': 'kne',			'type': 'application/vnd.kinar',															'description': 'Kinar Applications' },
	'kon': 			{ 'extension': 'kon',			'type': 'application/vnd.kde.kontour',														'description': 'KDE KOffice Office Suite - Kontour' },
	'kpr': 			{ 'extension': 'kpr',			'type': 'application/vnd.kde.kpresenter',													'description': 'KDE KOffice Office Suite - Kpresenter' },
	'ksp': 			{ 'extension': 'ksp',			'type': 'application/vnd.kde.kspread',														'description': 'KDE KOffice Office Suite - Kspread' },
	'ktx': 			{ 'extension': 'ktx',			'type': 'image/ktx',																		'description': 'OpenGL Textures (KTX)' },
	'ktz': 			{ 'extension': 'ktz',			'type': 'application/vnd.kahootz',															'description': 'Kahootz' },
	'kwd': 			{ 'extension': 'kwd',			'type': 'application/vnd.kde.kword',														'description': 'KDE KOffice Office Suite - Kword' },
	'lasxml': 		{ 'extension': 'lasxml',		'type': 'application/vnd.las.las+xml',														'description': 'Laser App Enterprise' },
	'latex': 		{ 'extension': 'latex',			'type': 'application/x-latex',																'description': 'LaTeX' },
	'lbd': 			{ 'extension': 'lbd',			'type': 'application/vnd.llamagraphics.life-balance.desktop',								'description': 'Life Balance - Desktop Edition' },
	'lbe': 			{ 'extension': 'lbe',			'type': 'application/vnd.llamagraphics.life-balance.exchange+xml',							'description': 'Life Balance - Exchange Format' },
	'les': 			{ 'extension': 'les',			'type': 'application/vnd.hhe.lesson-player',												'description': 'Archipelago Lesson Player' },
	'link66': 		{ 'extension': 'link66',		'type': 'application/vnd.route66.link66+xml',												'description': 'ROUTE 66 Location Based Services' },
	'lrm': 			{ 'extension': 'lrm',			'type': 'application/vnd.ms-lrm',															'description': 'Microsoft Learning Resource Module' },
	'ltf': 			{ 'extension': 'ltf',			'type': 'application/vnd.frogans.ltf',														'description': 'Frogans Player' },
	'lvp': 			{ 'extension': 'lvp',			'type': 'audio/vnd.lucent.voice',															'description': 'Lucent Voice' },
	'lwp': 			{ 'extension': 'lwp',			'type': 'application/vnd.lotus-wordpro',													'description': 'Lotus Wordpro' },
	'm21': 			{ 'extension': 'm21',			'type': 'application/mp21',																	'description': 'MPEG-21' },
	'm3u': 			{ 'extension': 'm3u',			'type': 'audio/x-mpegurl',																	'description': 'M3U (Multimedia Playlist)' },
	'm3u8': 		{ 'extension': 'm3u8',			'type': 'application/vnd.apple.mpegurl',													'description': 'Multimedia Playlist Unicode' },
	'm4v': 			{ 'extension': 'm4v',			'type': 'video/x-m4v',																		'description': 'M4v' },
	'ma': 			{ 'extension': 'ma',			'type': 'application/mathematica',															'description': 'Mathematica Notebooks' },
	'mads': 		{ 'extension': 'mads',			'type': 'application/mads+xml',																'description': 'Metadata Authority Description Schema' },
	'mag': 			{ 'extension': 'mag',			'type': 'application/vnd.ecowin.chart',														'description': 'EcoWin Chart' },
	'mathml': 		{ 'extension': 'mathml',		'type': 'application/mathml+xml',															'description': 'Mathematical Markup Language' },
	'mbk': 			{ 'extension': 'mbk',			'type': 'application/vnd.mobius.mbk',														'description': 'Mobius Management Systems - Basket file' },
	'mbox': 		{ 'extension': 'mbox',			'type': 'application/mbox',																	'description': 'Mbox database files' },
	'mc1': 			{ 'extension': 'mc1',			'type': 'application/vnd.medcalcdata',														'description': 'MedCalc' },
	'mcd': 			{ 'extension': 'mcd',			'type': 'application/vnd.mcd',																'description': 'Micro CADAM Helix D&D' },
	'mcurl': 		{ 'extension': 'mcurl',			'type': 'text/vnd.curl.mcurl',																'description': 'Curl - Manifest File' },
	'mdb': 			{ 'extension': 'mdb',			'type': 'application/x-msaccess',															'description': 'Microsoft Access' },
	'mdi': 			{ 'extension': 'mdi',			'type': 'image/vnd.ms-modi',																'description': 'Microsoft Document Imaging Format' },
	'meta4': 		{ 'extension': 'meta4',			'type': 'application/metalink4+xml',														'description': 'Metalink' },
	'mets': 		{ 'extension': 'mets',			'type': 'application/mets+xml',																'description': 'Metadata Encoding and Transmission Standard' },
	'mfm': 			{ 'extension': 'mfm',			'type': 'application/vnd.mfmp',																'description': 'Melody Format for Mobile Platform' },
	'mgp': 			{ 'extension': 'mgp',			'type': 'application/vnd.osgeo.mapguide.package',											'description': 'MapGuide DBXML' },
	'mgz': 			{ 'extension': 'mgz',			'type': 'application/vnd.proteus.magazine',													'description': 'EFI Proteus' },
	'mid': 			{ 'extension': 'mid',			'type': 'audio/midi',																		'description': 'MIDI - Musical Instrument Digital Interface' },
	'mif': 			{ 'extension': 'mif',			'type': 'application/vnd.mif',																'description': 'FrameMaker Interchange Format' },
	'mj2': 			{ 'extension': 'mj2',			'type': 'video/mj2',																		'description': 'Motion JPEG 2000' },
	'mlp': 			{ 'extension': 'mlp',			'type': 'application/vnd.dolby.mlp',														'description': 'Dolby Meridian Lossless Packing' },
	'mmd': 			{ 'extension': 'mmd',			'type': 'application/vnd.chipnuts.karaoke-mmd',												'description': 'Karaoke on Chipnuts Chipsets' },
	'mmf': 			{ 'extension': 'mmf',			'type': 'application/vnd.smaf',																'description': 'SMAF File' },
	'mmr': 			{ 'extension': 'mmr',			'type': 'image/vnd.fujixerox.edmics-mmr',													'description': 'EDMICS 2000' },
	'mny': 			{ 'extension': 'mny',			'type': 'application/x-msmoney',															'description': 'Microsoft Money' },
	'mods': 		{ 'extension': 'mods',			'type': 'application/mods+xml',																'description': 'Metadata Object Description Schema' },
	'movie': 		{ 'extension': 'movie',			'type': 'video/x-sgi-movie',																'description': 'SGI Movie' },
	'mp3': 			{ 'extension': 'mp3',			'type': 'audio/mpeg',																		'description': 'MPEG-2 Audio Layer III' },
	'mp4': 			{ 'extension': 'mp4',			'type': 'video/mp4',																		'description': 'MPEG-4 Video' },
	'mp4': 			{ 'extension': 'mp4',			'type': 'application/mp4',																	'description': 'MPEG4' },
	'mp4a': 		{ 'extension': 'mp4a',			'type': 'audio/mp4',																		'description': 'MPEG-4 Audio' },
	'mpc': 			{ 'extension': 'mpc',			'type': 'application/vnd.mophun.certificate',												'description': 'Mophun Certificate' },
	'mpeg': 		{ 'extension': 'mpeg',			'type': 'video/mpeg',																		'description': 'MPEG Video' },
	'mpga': 		{ 'extension': 'mpga',			'type': 'audio/mpeg',																		'description': 'MPEG Audio' },
	'mpkg': 		{ 'extension': 'mpkg',			'type': 'application/vnd.apple.installer+xml',												'description': 'Apple Installer Package' },
	'mpm': 			{ 'extension': 'mpm',			'type': 'application/vnd.blueice.multipass',												'description': 'Blueice Research Multipass' },
	'mpn': 			{ 'extension': 'mpn',			'type': 'application/vnd.mophun.application',												'description': 'Mophun VM' },
	'mpp': 			{ 'extension': 'mpp',			'type': 'application/vnd.ms-project',														'description': 'Microsoft Project' },
	'mpy': 			{ 'extension': 'mpy',			'type': 'application/vnd.ibm.minipay',														'description': 'MiniPay' },
	'mqy': 			{ 'extension': 'mqy',			'type': 'application/vnd.mobius.mqy',														'description': 'Mobius Management Systems - Query File' },
	'mrc': 			{ 'extension': 'mrc',			'type': 'application/marc',																	'description': 'MARC Formats' },
	'mrcx': 		{ 'extension': 'mrcx',			'type': 'application/marcxml+xml',															'description': 'MARC21 XML Schema' },
	'mscml': 		{ 'extension': 'mscml',			'type': 'application/mediaservercontrol+xml',												'description': 'Media Server Control Markup Language' },
	'mseq': 		{ 'extension': 'mseq',			'type': 'application/vnd.mseq',																'description': '3GPP MSEQ File' },
	'msf': 			{ 'extension': 'msf',			'type': 'application/vnd.epson.msf',														'description': 'QUASS Stream Player' },
	'msh': 			{ 'extension': 'msh',			'type': 'model/mesh',																		'description': 'Mesh Data Type' },
	'msl': 			{ 'extension': 'msl',			'type': 'application/vnd.mobius.msl',														'description': 'Mobius Management Systems - Script Language' },
	'msty': 		{ 'extension': 'msty',			'type': 'application/vnd.muvee.style',														'description': 'Muvee Automatic Video Editing' },
	'mts': 			{ 'extension': 'mts',			'type': 'model/vnd.mts',																	'description': 'Virtue MTS' },
	'mus': 			{ 'extension': 'mus',			'type': 'application/vnd.musician',															'description': 'MUsical Score Interpreted Code Invented for the ASCII designation of Notation' },
	'musicxml': 	{ 'extension': 'musicxml',		'type': 'application/vnd.recordare.musicxml+xml',											'description': 'Recordare Applications' },
	'mvb': 			{ 'extension': 'mvb',			'type': 'application/x-msmediaview',														'description': 'Microsoft MediaView' },
	'mwf': 			{ 'extension': 'mwf',			'type': 'application/vnd.mfer',																'description': 'Medical Waveform Encoding Format' },
	'mxf': 			{ 'extension': 'mxf',			'type': 'application/mxf',																	'description': 'Material Exchange Format' },
	'mxl': 			{ 'extension': 'mxl',			'type': 'application/vnd.recordare.musicxml',												'description': 'Recordare Applications' },
	'mxml': 		{ 'extension': 'mxml',			'type': 'application/xv+xml',																'description': 'MXML' },
	'mxs': 			{ 'extension': 'mxs',			'type': 'application/vnd.triscape.mxs',														'description': 'Triscape Map Explorer' },
	'mxu': 			{ 'extension': 'mxu',			'type': 'video/vnd.mpegurl',																'description': 'MPEG Url' },
	'n3': 			{ 'extension': 'n3',			'type': 'text/n3',																			'description': 'Notation3' },
	'nbp': 			{ 'extension': 'nbp',			'type': 'application/vnd.wolfram.player',													'description': 'Mathematica Notebook Player' },
	'nc': 			{ 'extension': 'nc',			'type': 'application/x-netcdf',																'description': 'Network Common Data Form (NetCDF)' },
	'ncx': 			{ 'extension': 'ncx',			'type': 'application/x-dtbncx+xml',															'description': 'Navigation Control file for XML (for ePub)' },
	'n': 			{ 'extension': 'n-gage',		'type': 'application/vnd.nokia.n-gage.symbian.install',										'description': 'N-Gage Game Installer' },
	'ngdat': 		{ 'extension': 'ngdat',			'type': 'application/vnd.nokia.n-gage.data',												'description': 'N-Gage Game Data' },
	'nlu': 			{ 'extension': 'nlu',			'type': 'application/vnd.neurolanguage.nlu',												'description': 'neuroLanguage' },
	'nml': 			{ 'extension': 'nml',			'type': 'application/vnd.enliven',															'description': 'Enliven Viewer' },
	'nnd': 			{ 'extension': 'nnd',			'type': 'application/vnd.noblenet-directory',												'description': 'NobleNet Directory' },
	'nns': 			{ 'extension': 'nns',			'type': 'application/vnd.noblenet-sealer',													'description': 'NobleNet Sealer' },
	'nnw': 			{ 'extension': 'nnw',			'type': 'application/vnd.noblenet-web',														'description': 'NobleNet Web' },
	'npx': 			{ 'extension': 'npx',			'type': 'image/vnd.net-fpx',																'description': 'FlashPix' },
	'nsf': 			{ 'extension': 'nsf',			'type': 'application/vnd.lotus-notes',														'description': 'Lotus Notes' },
	'oa2': 			{ 'extension': 'oa2',			'type': 'application/vnd.fujitsu.oasys2',													'description': 'Fujitsu Oasys' },
	'oa3': 			{ 'extension': 'oa3',			'type': 'application/vnd.fujitsu.oasys3',													'description': 'Fujitsu Oasys' },
	'oas': 			{ 'extension': 'oas',			'type': 'application/vnd.fujitsu.oasys',													'description': 'Fujitsu Oasys' },
	'obd': 			{ 'extension': 'obd',			'type': 'application/x-msbinder',															'description': 'Microsoft Office Binder' },
	'oda': 			{ 'extension': 'oda',			'type': 'application/oda',																	'description': 'Office Document Architecture' },
	'odb': 			{ 'extension': 'odb',			'type': 'application/vnd.oasis.opendocument.database',										'description': 'OpenDocument Database' },
	'odc': 			{ 'extension': 'odc',			'type': 'application/vnd.oasis.opendocument.chart',											'description': 'OpenDocument Chart' },
	'odf': 			{ 'extension': 'odf',			'type': 'application/vnd.oasis.opendocument.formula',										'description': 'OpenDocument Formula' },
	'odft': 		{ 'extension': 'odft',			'type': 'application/vnd.oasis.opendocument.formula-template',								'description': 'OpenDocument Formula Template' },
	'odg': 			{ 'extension': 'odg',			'type': 'application/vnd.oasis.opendocument.graphics',										'description': 'OpenDocument Graphics' },
	'odi': 			{ 'extension': 'odi',			'type': 'application/vnd.oasis.opendocument.image',											'description': 'OpenDocument Image' },
	'odm': 			{ 'extension': 'odm',			'type': 'application/vnd.oasis.opendocument.text-master',									'description': 'OpenDocument Text Master' },
	'odp': 			{ 'extension': 'odp',			'type': 'application/vnd.oasis.opendocument.presentation',									'description': 'OpenDocument Presentation' },
	'ods': 			{ 'extension': 'ods',			'type': 'application/vnd.oasis.opendocument.spreadsheet',									'description': 'OpenDocument Spreadsheet' },
	'odt': 			{ 'extension': 'odt',			'type': 'application/vnd.oasis.opendocument.text',											'description': 'OpenDocument Text' },
	'oga': 			{ 'extension': 'oga',			'type': 'audio/ogg',																		'description': 'Ogg Audio' },
	'ogg': 			{ 'extension': 'ogg',			'type': 'application/ogg',																	'description': 'Ogg' },
	'ogv': 			{ 'extension': 'ogv',			'type': 'video/ogg',																		'description': 'Ogg Video' },
	'ogx': 			{ 'extension': 'ogx',			'type': 'application/ogg',																	'description': 'Ogg' },
	'onetoc': 		{ 'extension': 'onetoc',		'type': 'application/onenote',																'description': 'Microsoft OneNote' },
	'opf': 			{ 'extension': 'opf',			'type': 'application/oebps-package+xml',													'description': 'Open eBook Publication Structure' },
	'org': 			{ 'extension': 'org',			'type': 'application/vnd.lotus-organizer',													'description': 'Lotus Organizer' },
	'osf': 			{ 'extension': 'osf',			'type': 'application/vnd.yamaha.openscoreformat',											'description': 'Open Score Format' },
	'osfpvg': 		{ 'extension': 'osfpvg',		'type': 'application/vnd.yamaha.openscoreformat.osfpvg+xml',								'description': 'OSFPVG' },
	'otc': 			{ 'extension': 'otc',			'type': 'application/vnd.oasis.opendocument.chart-template',								'description': 'OpenDocument Chart Template' },
	'otf': 			{ 'extension': 'otf',			'type': 'application/x-font-otf',															'description': 'OpenType Font File' },
	'otg': 			{ 'extension': 'otg',			'type': 'application/vnd.oasis.opendocument.graphics-template',								'description': 'OpenDocument Graphics Template' },
	'oth': 			{ 'extension': 'oth',			'type': 'application/vnd.oasis.opendocument.text-web',										'description': 'Open Document Text Web' },
	'oti': 			{ 'extension': 'oti',			'type': 'application/vnd.oasis.opendocument.image-template',								'description': 'OpenDocument Image Template' },
	'otp': 			{ 'extension': 'otp',			'type': 'application/vnd.oasis.opendocument.presentation-template',							'description': 'OpenDocument Presentation Template' },
	'ots': 			{ 'extension': 'ots',			'type': 'application/vnd.oasis.opendocument.spreadsheet-template',							'description': 'OpenDocument Spreadsheet Template' },
	'ott': 			{ 'extension': 'ott',			'type': 'application/vnd.oasis.opendocument.text-template',									'description': 'OpenDocument Text Template' },
	'oxt': 			{ 'extension': 'oxt',			'type': 'application/vnd.openofficeorg.extension',											'description': 'Open Office Extension' },
	'p': 			{ 'extension': 'p',				'type': 'text/x-pascal',																	'description': 'Pascal Source File' },
	'p10': 			{ 'extension': 'p10',			'type': 'application/pkcs10',																'description': 'PKCS #10 - Certification Request Standard' },
	'p12': 			{ 'extension': 'p12',			'type': 'application/x-pkcs12',																'description': 'PKCS #12 - Personal Information Exchange Syntax Standard' },
	'p7b': 			{ 'extension': 'p7b',			'type': 'application/x-pkcs7-certificates',													'description': 'PKCS #7 - Cryptographic Message Syntax Standard (Certificates)' },
	'p7m': 			{ 'extension': 'p7m',			'type': 'application/pkcs7-mime',															'description': 'PKCS #7 - Cryptographic Message Syntax Standard' },
	'p7r': 			{ 'extension': 'p7r',			'type': 'application/x-pkcs7-certreqresp',													'description': 'PKCS #7 - Cryptographic Message Syntax Standard (Certificate Request Response)' },
	'p7s': 			{ 'extension': 'p7s',			'type': 'application/pkcs7-signature',														'description': 'PKCS #7 - Cryptographic Message Syntax Standard' },
	'p8': 			{ 'extension': 'p8',			'type': 'application/pkcs8',																'description': 'PKCS #8 - Private-Key Information Syntax Standard' },
	'par': 			{ 'extension': 'par',			'type': 'text/plain-bas',																	'description': 'BAS Partitur Format' },
	'paw': 			{ 'extension': 'paw',			'type': 'application/vnd.pawaafile',														'description': 'PawaaFILE' },
	'pbd': 			{ 'extension': 'pbd',			'type': 'application/vnd.powerbuilder6',													'description': 'PowerBuilder' },
	'pbm': 			{ 'extension': 'pbm',			'type': 'image/x-portable-bitmap',															'description': 'Portable Bitmap Format' },
	'pcf': 			{ 'extension': 'pcf',			'type': 'application/x-font-pcf',															'description': 'Portable Compiled Format' },
	'pcl': 			{ 'extension': 'pcl',			'type': 'application/vnd.hp-pcl',															'description': 'HP Printer Command Language' },
	'pclxl': 		{ 'extension': 'pclxl',			'type': 'application/vnd.hp-pclxl',															'description': 'PCL 6 Enhanced (Formely PCL XL)' },
	'pcurl': 		{ 'extension': 'pcurl',			'type': 'application/vnd.curl.pcurl',														'description': 'CURL Applet' },
	'pcx': 			{ 'extension': 'pcx',			'type': 'image/x-pcx',																		'description': 'PCX Image' },
	'pdb': 			{ 'extension': 'pdb',			'type': 'application/vnd.palm',																'description': 'PalmOS Data' },
	'pdf': 			{ 'extension': 'pdf',			'type': 'application/pdf',																	'description': 'Adobe Portable Document Format' },
	'pfa': 			{ 'extension': 'pfa',			'type': 'application/x-font-type1',															'description': 'PostScript Fonts' },
	'pfr': 			{ 'extension': 'pfr',			'type': 'application/font-tdpfr',															'description': 'Portable Font Resource' },
	'pgm': 			{ 'extension': 'pgm',			'type': 'image/x-portable-graymap',															'description': 'Portable Graymap Format' },
	'pgn': 			{ 'extension': 'pgn',			'type': 'application/x-chess-pgn',															'description': 'Portable Game Notation (Chess Games)' },
	'pgp': 			{ 'extension': 'pgp',			'type': 'application/pgp-signature',														'description': 'Pretty Good Privacy - Signature' },
	'pic': 			{ 'extension': 'pic',			'type': 'image/x-pict',																		'description': 'PICT Image' },
	'pki': 			{ 'extension': 'pki',			'type': 'application/pkixcmp',																'description': 'Internet Public Key Infrastructure - Certificate Management Protocole' },
	'pkipath': 		{ 'extension': 'pkipath',		'type': 'application/pkix-pkipath',															'description': 'Internet Public Key Infrastructure - Certification Path' },
	'plb': 			{ 'extension': 'plb',			'type': 'application/vnd.3gpp.pic-bw-large',												'description': '3rd Generation Partnership Project - Pic Large' },
	'plc': 			{ 'extension': 'plc',			'type': 'application/vnd.mobius.plc',														'description': 'Mobius Management Systems - Policy Definition Language File' },
	'plf': 			{ 'extension': 'plf',			'type': 'application/vnd.pocketlearn',														'description': 'PocketLearn Viewers' },
	'pls': 			{ 'extension': 'pls',			'type': 'application/pls+xml',																'description': 'Pronunciation Lexicon Specification' },
	'pml': 			{ 'extension': 'pml',			'type': 'application/vnd.ctc-posml',														'description': 'PosML' },
	'png': 			{ 'extension': 'png',			'type': 'image/png',																		'description': 'Portable Network Graphics (PNG)' },
	'pnm': 			{ 'extension': 'pnm',			'type': 'image/x-portable-anymap',															'description': 'Portable Anymap Image' },
	'portpkg': 		{ 'extension': 'portpkg',		'type': 'application/vnd.macports.portpkg',													'description': 'MacPorts Port System' },
	'potm': 		{ 'extension': 'potm',			'type': 'application/vnd.ms-powerpoint.template.macroenabled.12',							'description': 'Micosoft PowerPoint - Macro-Enabled Template File' },
	'potx': 		{ 'extension': 'potx',			'type': 'application/vnd.openxmlformats-officedocument.presentationml.template',			'description': 'Microsoft Office - OOXML - Presentation Template' },
	'ppam': 		{ 'extension': 'ppam',			'type': 'application/vnd.ms-powerpoint.addin.macroenabled.12',								'description': 'Microsoft PowerPoint - Add-in file' },
	'ppd': 			{ 'extension': 'ppd',			'type': 'application/vnd.cups-ppd',															'description': 'Adobe PostScript Printer Description File Format' },
	'ppm': 			{ 'extension': 'ppm',			'type': 'image/x-portable-pixmap',															'description': 'Portable Pixmap Format' },
	'ppsm': 		{ 'extension': 'ppsm',			'type': 'application/vnd.ms-powerpoint.slideshow.macroenabled.12',							'description': 'Microsoft PowerPoint - Macro-Enabled Slide Show File' },
	'ppsx': 		{ 'extension': 'ppsx',			'type': 'application/vnd.openxmlformats-officedocument.presentationml.slideshow',			'description': 'Microsoft Office - OOXML - Presentation (Slideshow)' },
	'ppt': 			{ 'extension': 'ppt',			'type': 'application/vnd.ms-powerpoint',													'description': 'Microsoft PowerPoint' },
	'pptm': 		{ 'extension': 'pptm',			'type': 'application/vnd.ms-powerpoint.presentation.macroenabled.12',						'description': 'Microsoft PowerPoint - Macro-Enabled Presentation File' },
	'pptx': 		{ 'extension': 'pptx',			'type': 'application/vnd.openxmlformats-officedocument.presentationml.presentation',		'description': 'Microsoft Office - OOXML - Presentation' },
	'prc': 			{ 'extension': 'prc',			'type': 'application/x-mobipocket-ebook',													'description': 'Mobipocket' },
	'pre': 			{ 'extension': 'pre',			'type': 'application/vnd.lotus-freelance',													'description': 'Lotus Freelance' },
	'prf': 			{ 'extension': 'prf',			'type': 'application/pics-rules',															'description': 'PICSRules' },
	'psb': 			{ 'extension': 'psb',			'type': 'application/vnd.3gpp.pic-bw-small',												'description': '3rd Generation Partnership Project - Pic Small' },
	'psd': 			{ 'extension': 'psd',			'type': 'image/vnd.adobe.photoshop',														'description': 'Photoshop Document' },
	'psf': 			{ 'extension': 'psf',			'type': 'application/x-font-linux-psf',														'description': 'PSF Fonts' },
	'pskcxml': 		{ 'extension': 'pskcxml',		'type': 'application/pskc+xml',																'description': 'Portable Symmetric Key Container' },
	'ptid': 		{ 'extension': 'ptid',			'type': 'application/vnd.pvi.ptid1',														'description': 'Princeton Video Image' },
	'pub': 			{ 'extension': 'pub',			'type': 'application/x-mspublisher',														'description': 'Microsoft Publisher' },
	'pvb': 			{ 'extension': 'pvb',			'type': 'application/vnd.3gpp.pic-bw-var',													'description': '3rd Generation Partnership Project - Pic Var' },
	'pwn': 			{ 'extension': 'pwn',			'type': 'application/vnd.3m.post-it-notes',													'description': '3M Post It Notes' },
	'pya': 			{ 'extension': 'pya',			'type': 'audio/vnd.ms-playready.media.pya',													'description': 'Microsoft PlayReady Ecosystem' },
	'pyv': 			{ 'extension': 'pyv',			'type': 'video/vnd.ms-playready.media.pyv',													'description': 'Microsoft PlayReady Ecosystem Video' },
	'qam': 			{ 'extension': 'qam',			'type': 'application/vnd.epson.quickanime',													'description': 'QuickAnime Player' },
	'qbo': 			{ 'extension': 'qbo',			'type': 'application/vnd.intu.qbo',															'description': 'Open Financial Exchange' },
	'qfx': 			{ 'extension': 'qfx',			'type': 'application/vnd.intu.qfx',															'description': 'Quicken' },
	'qps': 			{ 'extension': 'qps',			'type': 'application/vnd.publishare-delta-tree',											'description': 'PubliShare Objects' },
	'qt': 			{ 'extension': 'qt',			'type': 'video/quicktime',																	'description': 'Quicktime Video' },
	'qxd': 			{ 'extension': 'qxd',			'type': 'application/vnd.quark.quarkxpress',												'description': 'QuarkXpress' },
	'ram': 			{ 'extension': 'ram',			'type': 'audio/x-pn-realaudio',																'description': 'Real Audio Sound' },
	'rar': 			{ 'extension': 'rar',			'type': 'application/x-rar-compressed',														'description': 'RAR Archive' },
	'ras': 			{ 'extension': 'ras',			'type': 'image/x-cmu-raster',																'description': 'CMU Image' },
	'rcprofile': 	{ 'extension': 'rcprofile',		'type': 'application/vnd.ipunplugged.rcprofile',											'description': 'IP Unplugged Roaming Client' },
	'rdf': 			{ 'extension': 'rdf',			'type': 'application/rdf+xml',																'description': 'Resource Description Framework' },
	'rdz': 			{ 'extension': 'rdz',			'type': 'application/vnd.data-vision.rdz',													'description': 'RemoteDocs R-Viewer' },
	'rep': 			{ 'extension': 'rep',			'type': 'application/vnd.businessobjects',													'description': 'BusinessObjects' },
	'res': 			{ 'extension': 'res',			'type': 'application/x-dtbresource+xml',													'description': 'Digital Talking Book - Resource File' },
	'rgb': 			{ 'extension': 'rgb',			'type': 'image/x-rgb',																		'description': 'Silicon Graphics RGB Bitmap' },
	'rif': 			{ 'extension': 'rif',			'type': 'application/reginfo+xml',															'description': 'IMS Networks' },
	'rip': 			{ 'extension': 'rip',			'type': 'audio/vnd.rip',																	'description': 'Hit\'n\'Mix' },
	'rl': 			{ 'extension': 'rl',			'type': 'application/resource-lists+xml',													'description': 'XML Resource Lists' },
	'rlc': 			{ 'extension': 'rlc',			'type': 'image/vnd.fujixerox.edmics-rlc',													'description': 'EDMICS 2000' },
	'rld': 			{ 'extension': 'rld',			'type': 'application/resource-lists-diff+xml',												'description': 'XML Resource Lists Diff' },
	'rm': 			{ 'extension': 'rm',			'type': 'application/vnd.rn-realmedia',														'description': 'RealMedia' },
	'rmp': 			{ 'extension': 'rmp',			'type': 'audio/x-pn-realaudio-plugin',														'description': 'Real Audio Sound' },
	'rms': 			{ 'extension': 'rms',			'type': 'application/vnd.jcp.javame.midlet-rms',											'description': 'Mobile Information Device Profile' },
	'rnc': 			{ 'extension': 'rnc',			'type': 'application/relax-ng-compact-syntax',												'description': 'Relax NG Compact Syntax' },
	'rp9': 			{ 'extension': 'rp9',			'type': 'application/vnd.cloanto.rp9',														'description': 'RetroPlatform Player' },
	'rpss': 		{ 'extension': 'rpss',			'type': 'application/vnd.nokia.radio-presets',												'description': 'Nokia Radio Application - Preset' },
	'rpst': 		{ 'extension': 'rpst',			'type': 'application/vnd.nokia.radio-preset',												'description': 'Nokia Radio Application - Preset' },
	'rq': 			{ 'extension': 'rq',			'type': 'application/sparql-query',															'description': 'SPARQL - Query' },
	'rs': 			{ 'extension': 'rs',			'type': 'application/rls-services+xml',														'description': 'XML Resource Lists' },
	'rsd': 			{ 'extension': 'rsd',			'type': 'application/rsd+xml',																'description': 'Really Simple Discovery' },
	'rss': 			{ 'extension': 'rss',			'type': 'application/rss+xml',																'description': 'RSS - Really Simple Syndication' },
	'rtf': 			{ 'extension': 'rtf',			'type': 'application/rtf',																	'description': 'Rich Text Format' },
	'rtx': 			{ 'extension': 'rtx',			'type': 'text/richtext',																	'description': 'Rich Text Format (RTF)' },
	's': 			{ 'extension': 's',				'type': 'text/x-asm',																		'description': 'Assembler Source File' },
	'saf': 			{ 'extension': 'saf',			'type': 'application/vnd.yamaha.smaf-audio',												'description': 'SMAF Audio' },
	'sbml': 		{ 'extension': 'sbml',			'type': 'application/sbml+xml',																'description': 'Systems Biology Markup Language' },
	'sc': 			{ 'extension': 'sc',			'type': 'application/vnd.ibm.secure-container',												'description': 'IBM Electronic Media Management System - Secure Container' },
	'scd': 			{ 'extension': 'scd',			'type': 'application/x-msschedule',															'description': 'Microsoft Schedule+' },
	'scm': 			{ 'extension': 'scm',			'type': 'application/vnd.lotus-screencam',													'description': 'Lotus Screencam' },
	'scq': 			{ 'extension': 'scq',			'type': 'application/scvp-cv-request',														'description': 'Server-Based Certificate Validation Protocol - Validation Request' },
	'scs': 			{ 'extension': 'scs',			'type': 'application/scvp-cv-response',														'description': 'Server-Based Certificate Validation Protocol - Validation Response' },
	'scurl': 		{ 'extension': 'scurl',			'type': 'text/vnd.curl.scurl',																'description': 'Curl - Source Code' },
	'sda': 			{ 'extension': 'sda',			'type': 'application/vnd.stardivision.draw',												'description': 'StarOffice - Draw' },
	'sdc': 			{ 'extension': 'sdc',			'type': 'application/vnd.stardivision.calc',												'description': 'StarOffice - Calc' },
	'sdd': 			{ 'extension': 'sdd',			'type': 'application/vnd.stardivision.impress',												'description': 'StarOffice - Impress' },
	'sdkm': 		{ 'extension': 'sdkm',			'type': 'application/vnd.solent.sdkm+xml',													'description': 'SudokuMagic' },
	'sdp': 			{ 'extension': 'sdp',			'type': 'application/sdp',																	'description': 'Session Description Protocol' },
	'sdw': 			{ 'extension': 'sdw',			'type': 'application/vnd.stardivision.writer',												'description': 'StarOffice - Writer' },
	'see': 			{ 'extension': 'see',			'type': 'application/vnd.seemail',															'description': 'SeeMail' },
	'seed': 		{ 'extension': 'seed',			'type': 'application/vnd.fdsn.seed',														'description': 'Digital Siesmograph Networks - SEED Datafiles' },
	'sema': 		{ 'extension': 'sema',			'type': 'application/vnd.sema',																'description': 'Secured eMail' },
	'semd': 		{ 'extension': 'semd',			'type': 'application/vnd.semd',																'description': 'Secured eMail' },
	'semf': 		{ 'extension': 'semf',			'type': 'application/vnd.semf',																'description': 'Secured eMail' },
	'ser': 			{ 'extension': 'ser',			'type': 'application/java-serialized-object',												'description': 'Java Serialized Object' },
	'setpay': 		{ 'extension': 'setpay',		'type': 'application/set-payment-initiation',												'description': 'Secure Electronic Transaction - Payment' },
	'setreg': 		{ 'extension': 'setreg',		'type': 'application/set-registration-initiation',											'description': 'Secure Electronic Transaction - Registration' },
	'sfd': 			{ 'extension': 'sfd-hdstx',		'type': 'application/vnd.hydrostatix.sof-data',												'description': 'Hydrostatix Master Suite' },
	'sfs': 			{ 'extension': 'sfs',			'type': 'application/vnd.spotfire.sfs',														'description': 'TIBCO Spotfire' },
	'sgl': 			{ 'extension': 'sgl',			'type': 'application/vnd.stardivision.writer-global',										'description': 'StarOffice - Writer (Global)' },
	'sgml': 		{ 'extension': 'sgml',			'type': 'text/sgml',																		'description': 'Standard Generalized Markup Language (SGML)' },
	'sh': 			{ 'extension': 'sh',			'type': 'application/x-sh',																	'description': 'Bourne Shell Script' },
	'shar': 		{ 'extension': 'shar',			'type': 'application/x-shar',																'description': 'Shell Archive' },
	'shf': 			{ 'extension': 'shf',			'type': 'application/shf+xml',																'description': 'S Hexdump Format' },
	'sis': 			{ 'extension': 'sis',			'type': 'application/vnd.symbian.install',													'description': 'Symbian Install Package' },
	'sit': 			{ 'extension': 'sit',			'type': 'application/x-stuffit',															'description': 'Stuffit Archive' },
	'sitx': 		{ 'extension': 'sitx',			'type': 'application/x-stuffitx',															'description': 'Stuffit Archive' },
	'skp': 			{ 'extension': 'skp',			'type': 'application/vnd.koan',																'description': 'SSEYO Koan Play File' },
	'sldm': 		{ 'extension': 'sldm',			'type': 'application/vnd.ms-powerpoint.slide.macroenabled.12',								'description': 'Microsoft PowerPoint - Macro-Enabled Open XML Slide' },
	'sldx': 		{ 'extension': 'sldx',			'type': 'application/vnd.openxmlformats-officedocument.presentationml.slide',				'description': 'Microsoft Office - OOXML - Presentation (Slide)' },
	'slt': 			{ 'extension': 'slt',			'type': 'application/vnd.epson.salt',														'description': 'SimpleAnimeLite Player' },
	'sm': 			{ 'extension': 'sm',			'type': 'application/vnd.stepmania.stepchart',												'description': 'StepMania' },
	'smf': 			{ 'extension': 'smf',			'type': 'application/vnd.stardivision.math',												'description': 'StarOffice - Math' },
	'smi': 			{ 'extension': 'smi',			'type': 'application/smil+xml',																'description': 'Synchronized Multimedia Integration Language' },
	'snf': 			{ 'extension': 'snf',			'type': 'application/x-font-snf',															'description': 'Server Normal Format' },
	'spf': 			{ 'extension': 'spf',			'type': 'application/vnd.yamaha.smaf-phrase',												'description': 'SMAF Phrase' },
	'spl': 			{ 'extension': 'spl',			'type': 'application/x-futuresplash',														'description': 'FutureSplash Animator' },
	'spot': 		{ 'extension': 'spot',			'type': 'text/vnd.in3d.spot',																'description': 'In3D - 3DML' },
	'spp': 			{ 'extension': 'spp',			'type': 'application/scvp-vp-response',														'description': 'Server-Based Certificate Validation Protocol - Validation Policies - Response' },
	'spq': 			{ 'extension': 'spq',			'type': 'application/scvp-vp-request',														'description': 'Server-Based Certificate Validation Protocol - Validation Policies - Request' },
	'src': 			{ 'extension': 'src',			'type': 'application/x-wais-source',														'description': 'WAIS Source' },
	'sru': 			{ 'extension': 'sru',			'type': 'application/sru+xml',																'description': 'Search/Retrieve via URL Response Format' },
	'srx': 			{ 'extension': 'srx',			'type': 'application/sparql-results+xml',													'description': 'SPARQL - Results' },
	'sse': 			{ 'extension': 'sse',			'type': 'application/vnd.kodak-descriptor',													'description': 'Kodak Storyshare' },
	'ssf': 			{ 'extension': 'ssf',			'type': 'application/vnd.epson.ssf',														'description': 'QUASS Stream Player' },
	'ssml': 		{ 'extension': 'ssml',			'type': 'application/ssml+xml',																'description': 'Speech Synthesis Markup Language' },
	'st': 			{ 'extension': 'st',			'type': 'application/vnd.sailingtracker.track',												'description': 'SailingTracker' },
	'stc': 			{ 'extension': 'stc',			'type': 'application/vnd.sun.xml.calc.template',											'description': 'OpenOffice - Calc Template (Spreadsheet)' },
	'std': 			{ 'extension': 'std',			'type': 'application/vnd.sun.xml.draw.template',											'description': 'OpenOffice - Draw Template (Graphics)' },
	'stf': 			{ 'extension': 'stf',			'type': 'application/vnd.wt.stf',															'description': 'Worldtalk' },
	'sti': 			{ 'extension': 'sti',			'type': 'application/vnd.sun.xml.impress.template',											'description': 'OpenOffice - Impress Template (Presentation)' },
	'stk': 			{ 'extension': 'stk',			'type': 'application/hyperstudio',															'description': 'Hyperstudio' },
	'stl': 			{ 'extension': 'stl',			'type': 'application/vnd.ms-pki.stl',														'description': 'Microsoft Trust UI Provider - Certificate Trust Link' },
	'str': 			{ 'extension': 'str',			'type': 'application/vnd.pg.format',														'description': 'Proprietary P&G Standard Reporting System' },
	'stw': 			{ 'extension': 'stw',			'type': 'application/vnd.sun.xml.writer.template',											'description': 'OpenOffice - Writer Template (Text - HTML)' },
	'sub': 			{ 'extension': 'sub',			'type': 'image/vnd.dvb.subtitle',															'description': 'Close Captioning - Subtitle' },
	'sus': 			{ 'extension': 'sus',			'type': 'application/vnd.sus-calendar',														'description': 'ScheduleUs' },
	'sv4cpio': 		{ 'extension': 'sv4cpio',		'type': 'application/x-sv4cpio',															'description': 'System V Release 4 CPIO Archive' },
	'sv4crc': 		{ 'extension': 'sv4crc',		'type': 'application/x-sv4crc',																'description': 'System V Release 4 CPIO Checksum Data' },
	'svc': 			{ 'extension': 'svc',			'type': 'application/vnd.dvb.service',														'description': 'Digital Video Broadcasting' },
	'svd': 			{ 'extension': 'svd',			'type': 'application/vnd.svd',																'description': 'SourceView Document' },
	'svg': 			{ 'extension': 'svg',			'type': 'image/svg+xml',																	'description': 'Scalable Vector Graphics (SVG)' },
	'swf': 			{ 'extension': 'swf',			'type': 'application/x-shockwave-flash',													'description': 'Adobe Flash' },
	'swi': 			{ 'extension': 'swi',			'type': 'application/vnd.aristanetworks.swi',												'description': 'Arista Networks Software Image' },
	'sxc': 			{ 'extension': 'sxc',			'type': 'application/vnd.sun.xml.calc',														'description': 'OpenOffice - Calc (Spreadsheet)' },
	'sxd': 			{ 'extension': 'sxd',			'type': 'application/vnd.sun.xml.draw',														'description': 'OpenOffice - Draw (Graphics)' },
	'sxg': 			{ 'extension': 'sxg',			'type': 'application/vnd.sun.xml.writer.global',											'description': 'OpenOffice - Writer (Text - HTML)' },
	'sxi': 			{ 'extension': 'sxi',			'type': 'application/vnd.sun.xml.impress',													'description': 'OpenOffice - Impress (Presentation)' },
	'sxm': 			{ 'extension': 'sxm',			'type': 'application/vnd.sun.xml.math',														'description': 'OpenOffice - Math (Formula)' },
	'sxw': 			{ 'extension': 'sxw',			'type': 'application/vnd.sun.xml.writer',													'description': 'OpenOffice - Writer (Text - HTML)' },
	't': 			{ 'extension': 't',				'type': 'text/troff',																		'description': 'troff' },
	'tao': 			{ 'extension': 'tao',			'type': 'application/vnd.tao.intent-module-archive',										'description': 'Tao Intent' },
	'tar': 			{ 'extension': 'tar',			'type': 'application/x-tar',																'description': 'Tar File (Tape Archive)' },
	'tcap': 		{ 'extension': 'tcap',			'type': 'application/vnd.3gpp2.tcap',														'description': '3rd Generation Partnership Project - Transaction Capabilities Application Part' },
	'tcl': 			{ 'extension': 'tcl',			'type': 'application/x-tcl',																'description': 'Tcl Script' },
	'teacher': 		{ 'extension': 'teacher',		'type': 'application/vnd.smart.teacher',													'description': 'SMART Technologies Apps' },
	'tei': 			{ 'extension': 'tei',			'type': 'application/tei+xml',																'description': 'Text Encoding and Interchange' },
	'tex': 			{ 'extension': 'tex',			'type': 'application/x-tex',																'description': 'TeX' },
	'texinfo': 		{ 'extension': 'texinfo',		'type': 'application/x-texinfo',															'description': 'GNU Texinfo Document' },
	'tfi': 			{ 'extension': 'tfi',			'type': 'application/thraud+xml',															'description': 'Sharing Transaction Fraud Data' },
	'tfm': 			{ 'extension': 'tfm',			'type': 'application/x-tex-tfm',															'description': 'TeX Font Metric' },
	'thmx': 		{ 'extension': 'thmx',			'type': 'application/vnd.ms-officetheme',													'description': 'Microsoft Office System Release Theme' },
	'tiff': 		{ 'extension': 'tiff',			'type': 'image/tiff',																		'description': 'Tagged Image File Format' },
	'tmo': 			{ 'extension': 'tmo',			'type': 'application/vnd.tmobile-livetv',													'description': 'MobileTV' },
	'torrent': 		{ 'extension': 'torrent',		'type': 'application/x-bittorrent',															'description': 'BitTorrent' },
	'tpl': 			{ 'extension': 'tpl',			'type': 'application/vnd.groove-tool-template',												'description': 'Groove - Tool Template' },
	'tpt': 			{ 'extension': 'tpt',			'type': 'application/vnd.trid.tpt',															'description': 'TRI Systems Config' },
	'tra': 			{ 'extension': 'tra',			'type': 'application/vnd.trueapp',															'description': 'True BASIC' },
	'trm': 			{ 'extension': 'trm',			'type': 'application/x-msterminal',															'description': 'Microsoft Windows Terminal Services' },
	'tsd': 			{ 'extension': 'tsd',			'type': 'application/timestamped-data',														'description': 'Time Stamped Data Envelope' },
	'tsv': 			{ 'extension': 'tsv',			'type': 'text/tab-separated-values',														'description': 'Tab Seperated Values' },
	'ttf': 			{ 'extension': 'ttf',			'type': 'application/x-font-ttf',															'description': 'TrueType Font' },
	'ttl': 			{ 'extension': 'ttl',			'type': 'text/turtle',																		'description': 'Turtle (Terse RDF Triple Language)' },
	'twd': 			{ 'extension': 'twd',			'type': 'application/vnd.simtech-mindmapper',												'description': 'SimTech MindMapper' },
	'txd': 			{ 'extension': 'txd',			'type': 'application/vnd.genomatix.tuxedo',													'description': 'Genomatix Tuxedo Framework' },
	'txf': 			{ 'extension': 'txf',			'type': 'application/vnd.mobius.txf',														'description': 'Mobius Management Systems - Topic Index File' },
	'txt': 			{ 'extension': 'txt',			'type': 'text/plain',																		'description': 'Text File' },
	'ufd': 			{ 'extension': 'ufd',			'type': 'application/vnd.ufdl',																'description': 'Universal Forms Description Language' },
	'umj': 			{ 'extension': 'umj',			'type': 'application/vnd.umajin',															'description': 'UMAJIN' },
	'unityweb': 	{ 'extension': 'unityweb',		'type': 'application/vnd.unity',															'description': 'Unity 3d' },
	'uoml': 		{ 'extension': 'uoml',			'type': 'application/vnd.uoml+xml',															'description': 'Unique Object Markup Language' },
	'uri': 			{ 'extension': 'uri',			'type': 'text/uri-list',																	'description': 'URI Resolution Services' },
	'ustar': 		{ 'extension': 'ustar',			'type': 'application/x-ustar',																'description': 'Ustar (Uniform Standard Tape Archive)' },
	'utz': 			{ 'extension': 'utz',			'type': 'application/vnd.uiq.theme',														'description': 'User Interface Quartz - Theme (Symbian)' },
	'uu': 			{ 'extension': 'uu',			'type': 'text/x-uuencode',																	'description': 'UUEncode' },
	'uva': 			{ 'extension': 'uva',			'type': 'audio/vnd.dece.audio',																'description': 'DECE Audio' },
	'uvh': 			{ 'extension': 'uvh',			'type': 'video/vnd.dece.hd',																'description': 'DECE High Definition Video' },
	'uvi': 			{ 'extension': 'uvi',			'type': 'image/vnd.dece.graphic',															'description': 'DECE Graphic' },
	'uvm': 			{ 'extension': 'uvm',			'type': 'video/vnd.dece.mobile',															'description': 'DECE Mobile Video' },
	'uvp': 			{ 'extension': 'uvp',			'type': 'video/vnd.dece.pd',																'description': 'DECE PD Video' },
	'uvs': 			{ 'extension': 'uvs',			'type': 'video/vnd.dece.sd',																'description': 'DECE SD Video' },
	'uvu': 			{ 'extension': 'uvu',			'type': 'video/vnd.uvvu.mp4',																'description': 'DECE MP4' },
	'uvv': 			{ 'extension': 'uvv',			'type': 'video/vnd.dece.video',																'description': 'DECE Video' },
	'vcd': 			{ 'extension': 'vcd',			'type': 'application/x-cdlink',																'description': 'Video CD' },
	'vcf': 			{ 'extension': 'vcf',			'type': 'text/x-vcard',																		'description': 'vCard' },
	'vcg': 			{ 'extension': 'vcg',			'type': 'application/vnd.groove-vcard',														'description': 'Groove - Vcard' },
	'vcs': 			{ 'extension': 'vcs',			'type': 'text/x-vcalendar',																	'description': 'vCalendar' },
	'vcx': 			{ 'extension': 'vcx',			'type': 'application/vnd.vcx',																'description': 'VirtualCatalog' },
	'vis': 			{ 'extension': 'vis',			'type': 'application/vnd.visionary',														'description': 'Visionary' },
	'viv': 			{ 'extension': 'viv',			'type': 'video/vnd.vivo',																	'description': 'Vivo' },
	'vsd': 			{ 'extension': 'vsd',			'type': 'application/vnd.visio',															'description': 'Microsoft Visio' },
	'vsf': 			{ 'extension': 'vsf',			'type': 'application/vnd.vsf',																'description': 'Viewport+' },
	'vtu': 			{ 'extension': 'vtu',			'type': 'model/vnd.vtu',																	'description': 'Virtue VTU' },
	'vxml': 		{ 'extension': 'vxml',			'type': 'application/voicexml+xml',															'description': 'VoiceXML' },
	'wad': 			{ 'extension': 'wad',			'type': 'application/x-doom',																'description': 'Doom Video Game' },
	'wav': 			{ 'extension': 'wav',			'type': 'audio/x-wav',																		'description': 'Waveform Audio File Format (WAV)' },
	'wax': 			{ 'extension': 'wax',			'type': 'audio/x-ms-wax',																	'description': 'Microsoft Windows Media Audio Redirector' },
	'wbmp': 		{ 'extension': 'wbmp',			'type': 'image/vnd.wap.wbmp',																'description': 'WAP Bitamp (WBMP)' },
	'wbs': 			{ 'extension': 'wbs',			'type': 'application/vnd.criticaltools.wbs+xml',											'description': 'Critical Tools - PERT Chart EXPERT' },
	'wbxml': 		{ 'extension': 'wbxml',			'type': 'application/vnd.wap.wbxml',														'description': 'WAP Binary XML (WBXML)' },
	'weba': 		{ 'extension': 'weba',			'type': 'audio/webm',																		'description': 'Open Web Media Project - Audio' },
	'webm': 		{ 'extension': 'webm',			'type': 'video/webm',																		'description': 'Open Web Media Project - Video' },
	'webp': 		{ 'extension': 'webp',			'type': 'image/webp',																		'description': 'WebP Image' },
	'wg': 			{ 'extension': 'wg',			'type': 'application/vnd.pmi.widget',														'description': 'Qualcomm\'s Plaza Mobile Internet' },
	'wgt': 			{ 'extension': 'wgt',			'type': 'application/widget',																'description': 'Widget Packaging and XML Configuration' },
	'wm': 			{ 'extension': 'wm',			'type': 'video/x-ms-wm',																	'description': 'Microsoft Windows Media' },
	'wma': 			{ 'extension': 'wma',			'type': 'audio/x-ms-wma',																	'description': 'Microsoft Windows Media Audio' },
	'wmd': 			{ 'extension': 'wmd',			'type': 'application/x-ms-wmd',																'description': 'Microsoft Windows Media Player Download Package' },
	'wmf': 			{ 'extension': 'wmf',			'type': 'application/x-msmetafile',															'description': 'Microsoft Windows Metafile' },
	'wml': 			{ 'extension': 'wml',			'type': 'text/vnd.wap.wml',																	'description': 'Wireless Markup Language (WML)' },
	'wmlc': 		{ 'extension': 'wmlc',			'type': 'application/vnd.wap.wmlc',															'description': 'Compiled Wireless Markup Language (WMLC)' },
	'wmls': 		{ 'extension': 'wmls',			'type': 'text/vnd.wap.wmlscript',															'description': 'Wireless Markup Language Script (WMLScript)' },
	'wmlsc': 		{ 'extension': 'wmlsc',			'type': 'application/vnd.wap.wmlscriptc',													'description': 'WMLScript' },
	'wmv': 			{ 'extension': 'wmv',			'type': 'video/x-ms-wmv',																	'description': 'Microsoft Windows Media Video' },
	'wmx': 			{ 'extension': 'wmx',			'type': 'video/x-ms-wmx',																	'description': 'Microsoft Windows Media Audio/Video Playlist' },
	'wmz': 			{ 'extension': 'wmz',			'type': 'application/x-ms-wmz',																'description': 'Microsoft Windows Media Player Skin Package' },
	'woff': 		{ 'extension': 'woff',			'type': 'application/x-font-woff',															'description': 'Web Open Font Format' },
	'wpd': 			{ 'extension': 'wpd',			'type': 'application/vnd.wordperfect',														'description': 'Wordperfect' },
	'wpl': 			{ 'extension': 'wpl',			'type': 'application/vnd.ms-wpl',															'description': 'Microsoft Windows Media Player Playlist' },
	'wps': 			{ 'extension': 'wps',			'type': 'application/vnd.ms-works',															'description': 'Microsoft Works' },
	'wqd': 			{ 'extension': 'wqd',			'type': 'application/vnd.wqd',																'description': 'SundaHus WQ' },
	'wri': 			{ 'extension': 'wri',			'type': 'application/x-mswrite',															'description': 'Microsoft Wordpad' },
	'wrl': 			{ 'extension': 'wrl',			'type': 'model/vrml',																		'description': 'Virtual Reality Modeling Language' },
	'wsdl': 		{ 'extension': 'wsdl',			'type': 'application/wsdl+xml',																'description': 'WSDL - Web Services Description Language' },
	'wspolicy': 	{ 'extension': 'wspolicy',		'type': 'application/wspolicy+xml',															'description': 'Web Services Policy' },
	'wtb': 			{ 'extension': 'wtb',			'type': 'application/vnd.webturbo',															'description': 'WebTurbo' },
	'wvx': 			{ 'extension': 'wvx',			'type': 'video/x-ms-wvx',																	'description': 'Microsoft Windows Media Video Playlist' },
	'x3d': 			{ 'extension': 'x3d',			'type': 'application/vnd.hzn-3d-crossword',													'description': '3D Crossword Plugin' },
	'xap': 			{ 'extension': 'xap',			'type': 'application/x-silverlight-app',													'description': 'Microsoft Silverlight' },
	'xar': 			{ 'extension': 'xar',			'type': 'application/vnd.xara',																'description': 'CorelXARA' },
	'xbap': 		{ 'extension': 'xbap',			'type': 'application/x-ms-xbap',															'description': 'Microsoft XAML Browser Application' },
	'xbd': 			{ 'extension': 'xbd',			'type': 'application/vnd.fujixerox.docuworks.binder',										'description': 'Fujitsu - Xerox DocuWorks Binder' },
	'xbm': 			{ 'extension': 'xbm',			'type': 'image/x-xbitmap',																	'description': 'X BitMap' },
	'xdf': 			{ 'extension': 'xdf',			'type': 'application/xcap-diff+xml',														'description': 'XML Configuration Access Protocol - XCAP Diff' },
	'xdm': 			{ 'extension': 'xdm',			'type': 'application/vnd.syncml.dm+xml',													'description': 'SyncML - Device Management' },
	'xdp': 			{ 'extension': 'xdp',			'type': 'application/vnd.adobe.xdp+xml',													'description': 'Adobe XML Data Package' },
	'xdssc': 		{ 'extension': 'xdssc',			'type': 'application/dssc+xml',																'description': 'Data Structure for the Security Suitability of Cryptographic Algorithms' },
	'xdw': 			{ 'extension': 'xdw',			'type': 'application/vnd.fujixerox.docuworks',												'description': 'Fujitsu - Xerox DocuWorks' },
	'xenc': 		{ 'extension': 'xenc',			'type': 'application/xenc+xml',																'description': 'XML Encryption Syntax and Processing' },
	'xer': 			{ 'extension': 'xer',			'type': 'application/patch-ops-error+xml',													'description': 'XML Patch Framework' },
	'xfdf': 		{ 'extension': 'xfdf',			'type': 'application/vnd.adobe.xfdf',														'description': 'Adobe XML Forms Data Format' },
	'xfdl': 		{ 'extension': 'xfdl',			'type': 'application/vnd.xfdl',																'description': 'Extensible Forms Description Language' },
	'xhtml': 		{ 'extension': 'xhtml',			'type': 'application/xhtml+xml',															'description': 'XHTML - The Extensible HyperText Markup Language' },
	'xif': 			{ 'extension': 'xif',			'type': 'image/vnd.xiff',																	'description': 'eXtended Image File Format (XIFF)' },
	'xlam': 		{ 'extension': 'xlam',			'type': 'application/vnd.ms-excel.addin.macroenabled.12',									'description': 'Microsoft Excel - Add-In File' },
	'xls': 			{ 'extension': 'xls',			'type': 'application/vnd.ms-excel',															'description': 'Microsoft Excel' },
	'xlsb': 		{ 'extension': 'xlsb',			'type': 'application/vnd.ms-excel.sheet.binary.macroenabled.12',							'description': 'Microsoft Excel - Binary Workbook' },
	'xlsm': 		{ 'extension': 'xlsm',			'type': 'application/vnd.ms-excel.sheet.macroenabled.12',									'description': 'Microsoft Excel - Macro-Enabled Workbook' },
	'xlsx': 		{ 'extension': 'xlsx',			'type': 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',				'description': 'Microsoft Office - OOXML - Spreadsheet' },
	'xltm': 		{ 'extension': 'xltm',			'type': 'application/vnd.ms-excel.template.macroenabled.12',								'description': 'Microsoft Excel - Macro-Enabled Template File' },
	'xltx': 		{ 'extension': 'xltx',			'type': 'application/vnd.openxmlformats-officedocument.spreadsheetml.template',				'description': 'Microsoft Office - OOXML - Spreadsheet Teplate' },
	'xml': 			{ 'extension': 'xml',			'type': 'application/xml',																	'description': 'XML - Extensible Markup Language' },
	'xo': 			{ 'extension': 'xo',			'type': 'application/vnd.olpc-sugar',														'description': 'Sugar Linux Application Bundle' },
	'xop': 			{ 'extension': 'xop',			'type': 'application/xop+xml',																'description': 'XML-Binary Optimized Packaging' },
	'xpi': 			{ 'extension': 'xpi',			'type': 'application/x-xpinstall',															'description': 'XPInstall - Mozilla' },
	'xpm': 			{ 'extension': 'xpm',			'type': 'image/x-xpixmap',																	'description': 'X PixMap' },
	'xpr': 			{ 'extension': 'xpr',			'type': 'application/vnd.is-xpr',															'description': 'Express by Infoseek' },
	'xps': 			{ 'extension': 'xps',			'type': 'application/vnd.ms-xpsdocument',													'description': 'Microsoft XML Paper Specification' },
	'xpw': 			{ 'extension': 'xpw',			'type': 'application/vnd.intercon.formnet',													'description': 'Intercon FormNet' },
	'xslt': 		{ 'extension': 'xslt',			'type': 'application/xslt+xml',																'description': 'XML Transformations' },
	'xsm': 			{ 'extension': 'xsm',			'type': 'application/vnd.syncml+xml',														'description': 'SyncML' },
	'xspf': 		{ 'extension': 'xspf',			'type': 'application/xspf+xml',																'description': 'XSPF - XML Shareable Playlist Format' },
	'xul': 			{ 'extension': 'xul',			'type': 'application/vnd.mozilla.xul+xml',													'description': 'XUL - XML User Interface Language' },
	'xwd': 			{ 'extension': 'xwd',			'type': 'image/x-xwindowdump',																'description': 'X Window Dump' },
	'xyz': 			{ 'extension': 'xyz',			'type': 'chemical/x-xyz',																	'description': 'XYZ File Format' },
	'yaml': 		{ 'extension': 'yaml',			'type': 'text/yaml',																		'description': 'YAML Ain\'t Markup Language / Yet Another Markup Language' },
	'yang': 		{ 'extension': 'yang',			'type': 'application/yang',																	'description': 'YANG Data Modeling Language' },
	'yin': 			{ 'extension': 'yin',			'type': 'application/yin+xml',																'description': 'YIN (YANG - XML)' },
	'zaz': 			{ 'extension': 'zaz',			'type': 'application/vnd.zzazz.deck+xml',													'description': 'Zzazz Deck' },
	'zip': 			{ 'extension': 'zip',			'type': 'application/zip',																	'description': 'Zip Archive' },
	'zir': 			{ 'extension': 'zir',			'type': 'application/vnd.zul',																'description': 'Z.U.L. Geometry' },
	'zmm': 			{ 'extension': 'zmm',			'type': 'application/vnd.handheld-entertainment+xml',																		'description': 'ZVUE Media Manager' }
};

// Export
export default FileFormats;
